services:
  db:
    image: mysql:8.0.27
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: "exit 0"
    #volume
  
  trainit:
    image: trueberryless/trainit
    ports:
      - "80:80"
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

networks:
  db: { }
  
  